### ISSUE TITLE
Joint inference with fixed parameters

### ISSUE THREAD

**Issue by AudeCaizergues** [Sendrowski/fastDFE#11]
Hello,

I am trying to run a joint inference from the SFS of 2 different populations and I have some questions regarding the process.

1. From the nature of my data and my questions, I only want to estimate purifying selection occurring in my 2 populations. I understand that we can constrain parameters to do so such as p_b=0 so that S can't be positive.
In the manual however (section DFE inference > Base inference > Fixing parameters), I read that "We also force the DFE to be purely deleterious, by fixing S_b to some arbitrary value and setting p_b to 0". I understand why we fix p_b to 0 but I wonder why we necessarily have to fix S_b=1 (in this case) to achieve the estimation of only deleterious mutations. Could you please elaborate on that ?

2. I found no example combining joint inference with fixing parameters so I code my script like that (where eps is shared and p_b fixed to 0, I'll add S_b=1 if need be):

```
inf = fd.JointInference(
    sfs_neut=sfs_neut,
    sfs_sel=sfs_sel,
    shared_params=[fd.SharedParams(types=["urb", "rur"], params=["eps"])], #share the sames ancestral allele misidentification rate
    fixed_params=dict(all=dict(p_b=0)), # fixed so we only infer purif selection
    do_bootstrap=True
)
```
Is it the proper way to (visually) test some difference in selection between my populations ?

3. In addition with plotting the results of selection from my SFS, I would like to formally test if my patterns of selection in each population are significantly different from each other (e.g., if purifying selection is stronger in one of the populations). I see the function "inf.perform_lrt_shared()" which in your example gives a Pvalue = 0.451 (I guess it's a Pvalue at least), and you mention that "The test is not significant, indicating that the simpler model of sharing the parameters explains the data sufficiently well. Indeed, we do not observe a lot of differences between the inferred parameters of joint and the marginal inferences."

When I run this test on my data I get: 
```
>>> inf.perform_lrt_shared()
INFO:JointInference: Simple model likelihood: -235.27340578049512, complex model likelihood: -235.14460149932972, degrees of freedom: 1.
0.6117678851908046
```
But I have a hard time figuring out what it means in terms of eps and p_b and hesitate between two interpretations : 
    - (1) eps does not vary between my populations (but we can't interpret anything as far as S is concerned, and we just use the graph with confidence intervals)
    - (2) eps AND S do not differ between populations 
I would really appreciate if you could enlighten me about how to interpret such a result, as I'm quite confused...

Thank you in advance for your help,

Aude

**Comment by Sendrowski** [comment]
Hi Aude,

1. The idea is to fix `S_b` to an arbitrary value to avoid optimizing an unneeded (and unidentifiable) parameter when fixing `p_b` to 0.
2. Yes, I think that should do the trick. In addition, I would also fix `S_b` to an arbitrary value here, and of course check if they were indeed held fixed by inspecting [`JointInference.params_mle`](https://fastdfe.readthedocs.io/en/latest/modules/inference.html#fastdfe.joint_inference.JointInference.params_mle).
3. The likelihood of the more complex model (with more parameters) is obtained by summing up the log likelihoods of the `marginal` component spectra (types `"urb"` and `"rur"` in your case). You can obtain the marginal inference objects by accessing [`JointInference.marginal_inferences`](https://fastdfe.readthedocs.io/en/latest/modules/inference.html#fastdfe.joint_inference.JointInference.marginal_inferences) which is a dictionary of `BaseInference` objects for the different types. (You can ignore the `"all"` entry which is the `BaseInference` results for the sum of all component spectra.) The marginal inference inherit the fixed parameters from `JointInference` (which can you verify by checking [`JointInference.marginal_inferences[type].fixed_params`](https://fastdfe.readthedocs.io/en/latest/modules/inference.html#fastdfe.base_inference.BaseInference.fixed_params)), so what you're effectively testing is whether `eps` varies between rural and urban populations (which might not be so informative after all). If you want to test whether purifying selection differs, you would share `S_d` or `b` or both between your types.

I hope this helps
Janek

**Comment by AudeCaizergues** [comment]
Hello,

Thank you for your reply, that was very helpful !
I followed your advice to fix S_b to 1, and performed my model with shared parameters to have the good LRT test. I also checked my parameter estimations as you suggested, and the model followed well my constraints so all good!
I have a final question for you now, I would like to extract the values that are used by plot_inferred_parameters() and plot_discretized() functions so I can plot with my own graph aesthetic. I'm able to extract the mean value, but I can't manage to find the confidence intervals that they show (by the way is it 95% CI ?).
Thank you,

Aude

**Comment by Sendrowski** [comment]
Hi Aude,

I’m glad it all worked out for you! You can access the inferred parameters for all individuals bootstrap by [`JointInference.bootstraps`](https://fastdfe.readthedocs.io/en/latest/modules/inference.html#fastdfe.joint_inference.JointInference.bootstraps), and the parameter confidence intervals and discretized DFE by using [JointInference.get_cis_params_mle](https://fastdfe.readthedocs.io/en/latest/modules/inference.html#fastdfe.abstract_inference.Inference.get_cis_params_mle) and [JointInference.get_discretized](https://fastdfe.readthedocs.io/en/latest/modules/inference.html#fastdfe.abstract_inference.Inference.get_discretized), respectively. Both methods allow you to configure the confidence threshold.

Janek

**Comment by AudeCaizergues** [comment]
Hi Janek,

Very helpful functions thank you ! 
I have a (verey last, I hope) question regarding the value to use as estimate of S_d and b to use. The results provide both the marginal and the joint estimates, and I was wondering which one is the "true" measure of the parameters?
Thanks,

Aude
