### ISSUE TITLE
Joint DFE inference on spectra of different size

### ISSUE THREAD

**Issue by AudeCaizergues** [Sendrowski/fastDFE#12]
Hello,

I am trying to run a joint inference on two populations with different sample sizes (20 vs. 17) and I get an error from the spectra definition step telling me that arrays must be of the same length. Is there a way to perform a joint inference on different size spectra? 

```
"raise ValueError("All arrays must be of the same length")
ValueError: All arrays must be of the same length "
```
FYI, I'm using this script below (but with different SFS):

```
# neutral SFS for two types
sfs_neut = fd.Spectra(dict(
    pendula=[177130, 997, 441, 228, 156, 117, 114, 83, 105, 109, 652],
    pubescens=[172528, 3612, 1359, 790, 584, 427, 325, 234, 166, 76, 31]
))
# selected SFS for two types
sfs_sel = fd.Spectra(dict(
    pendula=[797939, 1329, 499, 265, 162, 104, 117, 90, 94, 119, 794],
    pubescens=[791106, 5326, 1741, 1005, 756, 546, 416, 294, 177, 104, 41]
))
# create inference object
inf = fd.JointInference(
    sfs_neut=sfs_neut,
    sfs_sel=sfs_sel,
    shared_params=[fd.SharedParams(types=["pendula", "pubescens"], params=["eps", "S_d"])],
    do_bootstrap=True
)
# run inference
inf.run();
```
Thanks,

Aude 

PS: I'm opening a new conversation here as this topic is unrelated to my previous question and might interest other readers in the future.

**Comment by Sendrowski** [comment]
Hi Aude,

while it would be possible in principle to support joint inference with spectra of difference sizes per type, this is currently not implemented. I suggest downsampling the spectra to the same sample size. You can also use [`Spectra.subsample`](https://fastdfe.readthedocs.io/en/latest/modules/spectra.html#fastdfe.spectrum.Spectra.subsample) to this end.

Janek

**Comment by AudeCaizergues** [comment]
Hi,

Thanks for the precision! From what I understand, if I use the probabilistic mode I'll get always the same subsample of my SFS but if I use random I will get a random subsample. Could you develop on what is based the 'probabilistic' method? If I understand correctly these subsampling methods are not per se removing individuals but adjusting the mutation "bins" to mimic what we would get if we had N less individuals right?
Do you have any insight on the robustness of such an approach rather than randomly removing individuals before parsing my VCF for the SFS ? 
I see one advantage of the SFS subsampling option that it allows for a straightforward estimation of the DFE without having to replicate 100 or 1000 times the downsampling (from VCF or with the 'random' option). But I might be mistaking...
Thanks!

Aude

**Comment by Sendrowski** [comment]
Hi Aude,

the `probabilistic` subsampling of [`Spectra.subsample`](https://fastdfe.readthedocs.io/en/latest/modules/spectra.html#fastdfe.spectrum.Spectra.subsample) is hypergeometric (drawing without replacement), so we add up the hypergeometric distribution for all bins. This will give the same result as if one had used [`Parser`](https://fastdfe.readthedocs.io/en/latest/modules/parser.html#fastdfe.parser.Parser) directly with the subsample size (subsampling is also hypergeometric for [`Parser`](https://fastdfe.readthedocs.io/en/latest/modules/parser.html#fastdfe.parser.Parser)). I don’t recommend the `random` mode of [`Spectra.subsample`](https://fastdfe.readthedocs.io/en/latest/modules/spectra.html#fastdfe.spectrum.Spectra.subsample). It is mainly there for legacy reasons.

If you instead subsample the set of individuals in the VCF, then you will end up with fewer sites depending on missingness since all sites for which the subsample size is larger than the number of called genotypes are ignored. When bootstrapping, we resample use the Poisson distribution (see [`Spectrum.resample`](https://fastdfe.readthedocs.io/en/latest/modules/spectrum.html#fastdfe.spectrum.Spectrum.resample)).

Janek
