### ISSUE TITLE
how to use skip_not_polarized

### ISSUE THREAD

**Issue by zhangming-m** [Sendrowski/fastDFE#3]
this is my code:
p <- fd$Parser(
  n = 8,
  vcf = paste0( "/Users/macbookair/Desktop/evodevo/reseq/all_file_snp_flt.vcf.gz"),
  fasta = paste0( "/Users/macbookair/Desktop/evodevo/reseq/单倍型网络/all_flt_variants_outgr.min4.fasta"),
  gff = paste0( "/Users/macbookair/Desktop/evodevo/genome/augustus.merged_missGenes.srt.gff3"),
  annotations = c(
    fd$DegeneracyAnnotation()
  ),
  stratifications = c(fd$DegeneracyStratification())
)

spectra <- fd$Parser$parse(p)

WARNING:Parser: Your variants might not be polarized and thus not included in the spectra. If this is the case, consider using an ancestral allele annotation or setting 'skip_non_polarized' to False.

**i'd like to try the skip_non_polarized function**  but don't know how to use it,can not find any guidance

**Comment by Sendrowski** [comment]
Hey!

By default, sites that do not contain information on the ancestral allele are ignored. You're getting this warning, because in your case, no sites in your VCF file contained ancestral allele information so that all of them were skipped. Have you tried setting `skip_non_polarized` to `False`, as the warning suggests? In this case, non-polarized sites won't be skipped. You can read more about that in the [API reference](https://fastdfe.readthedocs.io/en/latest/modules/parser.html#fastdfe.parser.Parser.__init__).

**Comment by Sendrowski** [comment]
I will close this issue for now. Should you have more questions, feel free to reopen this issue or create another one.
